name: anomaly-predictor
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    value: ${OPENAI_API_KEY}
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 10
  instance_count: 1
  instance_size_slug: basic-xxs
  run_command: gunicorn --workers 3 --bind 0.0.0.0:$PORT app:app 